# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# Create single node Spectrum Scale cluster
#

$message = <<EOT
--------------------------------------------------------------------------

Created virtual environment for IBM Spectrum Scale.

User Guide:
https://github.com/IBM/SpectrumScaleVagrant/blob/master/README.md

To logon on the management node execute:
vagrant ssh

To connect to the Spectrum Scale GUI, in a web browser:
https://localhost:8888

--------------------------------------------------------------------------
EOT


# Set provider
$SpectrumScaleVagrant_provider = 'VirtualBox'


# Load common settings
load File.expand_path('../../shared/Vagrantfile.common', __FILE__)

# Customize configuration specific settings
Vagrant.configure("2") do |config|

  # Use the Vagrant box prepared for Spectrum Scale
  config.vm.box     = "SpectrumScale_base"
  config.vm.box_url = "./prep-box/SpectrumScale_base.box"

  # Customize resources of virtual machines
  config.vm.provider "virtualbox" do |vbox|
    vbox.memory = 2048
    vbox.cpus = 2
  end

  # the kernel that the base build uses is incopatible with SpectrumScale, I get the following error
  # m1: [ FATAL ] m1.example.com: Pre requisite packages not found on m1.example.com
  #   (Pre requisites: kernel-devel-3.10.0-1127.el7.x86_64, kernel-headers-3.10.0-1127.el7.x86_64).
  #   Ensure this is resolved before proceeding with the install toolkit.
  # Ideally we could just run:
  # So here we remove the newer kernel-devel and kernel-headers and install the older versions specifically
  # Since the old versions aren't in the yum repos we manually install them with rpm. And then reinstall gcc
  # since it was uninstalled when we removed the old kernel
  config.vm.provision "shell",
  name:   "Remove installed kernel-devel and kernel-headers to prevent version missmatches",
  inline: "
    /usr/bin/yum remove -y\
      kernel-devel\
      kernel-headers\
  "
  config.vm.provision "shell",
    name: "Install kernel-devel-3.10.0-1127.el7.x86_64.rpm",
    inline: "sudo rpm -i http://linuxsoft.cern.ch/cern/centos/7/updates/x86_64/Packages/Packages/kernel-devel-3.10.0-1127.el7.x86_64.rpm --oldpackage"

  config.vm.provision "shell",
    name: "Install kernel-headers-3.10.0-1127.el7.x86_64.rpm",
    inline: "sudo rpm -i http://linuxsoft.cern.ch/cern/centos/7/updates/x86_64/Packages/Packages/kernel-headers-3.10.0-1127.el7.x86_64.rpm --oldpackage"

  # Install RPMs required by Spectrum Scale to build portability layer
  config.vm.provision "shell",
    name:   "Install RPMs required by Spectrum Scale to build portability layer",
    inline: "
      /usr/bin/yum install -y\
        cpp\
        gcc\
        gcc-c++
    "

  #
  # The single node cluster comprises one node only
  #

  config.vm.define "m1", primary: true do |node|
    node.vm.hostname = "m1"
    node.vm.network "private_network", ip: "10.1.1.11"  
    node.vm.network "private_network", ip: "10.1.2.11" 
    node.vm.network "forwarded_port", guest: 443, host: 8888

    # Attach five disks for Spectrum Scale NSDs
    node.vm.provider "virtualbox" do |vbox|
      vbox.customize ['storagectl', :id, '--name', 'SATA', '--add', 'sata', '--hostiocache', 'off']
      small = 5
      (1..small).each do |disk|
        filename = "disk/disk-m1-00#{disk}.vdi"
        unless File.exist?(filename)
          vbox.customize ['createhd', '--format', 'vdi', '--variant', 'fixed', '--filename', filename, '--size', 2 * 1024]
        end
        vbox.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', "#{disk-1}", '--device', 0, '--type', 'hdd', '--medium', filename]
      end
      large = 2
      (small+1..small+large).each do |disk|
        filename = "disk/disk-m1-00#{disk}.vdi"
        unless File.exist?(filename)
          vbox.customize ['createhd', '--format', 'vdi', '--variant', 'fixed', '--filename', filename, '--size', 10 * 1024]
        end
        vbox.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', "#{disk-1}", '--device', 0, '--type', 'hdd', '--medium', filename]
      end
    end

    # Set message to be printed after VMs are up and running
    config.vm.post_up_message = $message

    # Sync Spectrum Scale install package to admin node
    config.vm.synced_folder "../software", "/software", type: "rsync"

    # Install and configure single node Spectrum Scale cluster
    node.vm.provision "shell",
      name:   "Install and configure single node Spectrum Scale cluster",
      inline: "
        /vagrant/install/script.sh #{$SpectrumScaleVagrant_provider}
      "

    # Configure Spectrum Scale for demo purposes
    node.vm.provision "shell",
      name:   "Configure Spectrum Scale for demo purposes",
      inline: "
        /vagrant/demo/script.sh
      "

  end

end


